### ISSUE TITLE
Bundle installation does not work as expected

### ISSUE THREAD

**Issue by tacman** [ajgarlag/AjglBreakpointTwigExtension#14]
```bash
 symfony new --webapp breakpoint-demo && cd breakpoint-demo
composer require ajgl/breakpoint-twig-extension
bin/console debug:twig | grep -i breakpoint
```

It isn't installed in bundles.php either, nor can you do it manually, since the bundle class isn't loaded.

**Comment by ajgarlag** [comment]
The bundle is not registered automatically. You have to add it manually in your `bundles.php` file. See: https://github.com/ajgarlag/AjglBreakpointTwigExtension#symfony-456

I think that a Flex recipe is required to register the bundle automatically. Any contribution is welcome.

**Comment by ajgarlag** [comment]
See https://github.com/symfony/recipes-contrib/pull/1457

**Comment by ajgarlag** [comment]
@tacman The recipe PR has been finally merged, so the bundle is enabled by default if you use `symfony/flex`
