### ISSUE TITLE
Drop Unsupported Symfony, add Symfony 7, Twig 4

### ISSUE THREAD

**Issue by tacman** [ajgarlag/AjglBreakpointTwigExtension#18]
Please add Symfony 7, and I think you could drop 4.4, and only support ^5.4 || ^6.3 || ^7.0

Also, Twig 2 is EOL, and Twig 4 is close.

**Comment by ajgarlag** [comment]
The bundle is already compatible with Symfony 7.0

I'll try to add support for Twig 4 soon, or maybe you can contribute with a PR.

**Comment by ajgarlag** [comment]
Twig 4 and full Symfony 7 support added in version 0.4.2

I'll drop support for old Twig, Symfony and PHP versions soo.
