### ISSUE TITLE
Twig 2.0 Support

### ISSUE THREAD

**Issue by inoas** [ajgarlag/AjglBreakpointTwigExtension#4]
Is this being planned anytime soon?

**Comment by ajgarlag** [comment]
Thanks for your interest.

It's planned, but I'm too busy. Maybe you can contribute with a PR.

**Comment by fgm** [comment]
Is it actually broken, or just a matter of updating the repo ?

**Comment by ajgarlag** [comment]
Can you test it changing your required version for `ajgl/breakpoint-twig-extension` to `dev-twig2`?

```json
{
     "require": {
        "ajgl/breakpoint-twig-extension": "dev-twig2"
    }
}
```

**Comment by pbowyer** [comment]
@ajgarlag `dev-twig2` works for me with Twig 2.X, thanks.

**Comment by ajgarlag** [comment]
Thanks @pbowyer. I'll try to tag a new release as soon as posible.

**Comment by inoas** [comment]
ping @WyriHaximus
