### ISSUE TITLE
Support Symfony 4

### ISSUE THREAD

**Issue by garak** [ajgarlag/AjglBreakpointTwigExtension#6]

**Comment by ajgarlag** [comment]
What problem do you have?

**Comment by garak** [comment]
Can't install with Symfony 4

**Comment by garak** [comment]
I guess you should change dev requirements in composer to test if this is working with Symfony 4

**Comment by ajgarlag** [comment]
Can you paste the error message produced by composer? I cannot reproduce your problem.

**Comment by garak** [comment]
There's no error.
